services:
  - type: worker
    name: skyspotter-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
